<template>
  <div class="translation-warning">
    <div class="warning-icon">⚠️</div>
    <div class="warning-content">
      <strong>Machine Translated Content</strong>
      <p>This page content is generated by machine translation and may contain inaccuracies. If you find any issues, please feel free to submit feedback or contribute more accurate translations.</p>
    </div>
  </div>
</template>

<style scoped>
.translation-warning {
  display: flex;
  align-items: flex-start;
  gap: 12px;
  padding: 16px;
  margin: 16px 0;
  background-color: var(--vp-c-warning-soft);
  border: 1px solid var(--vp-c-warning);
  border-radius: 8px;
}

.warning-icon {
  font-size: 20px;
  flex-shrink: 0;
}

.warning-content {
  flex: 1;
}

.warning-content strong {
  color: var(--vp-c-warning-text);
  display: block;
  margin-bottom: 4px;
}

.warning-content p {
  margin: 0;
  color: var(--vp-c-text-2);
  font-size: 14px;
  line-height: 1.4;
}
</style>